apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaychang99-cicd
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jaychang99/gitops
  newTag: "74"
