apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaychang99-cicd-prod
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jaychang99/gitops
  newTag: a12bd550f87e69808fb6ed3d337411af9b56090b
